apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: springio
spec:
  type: ExternalName
  externalName: mysql.db.svc.cluster.local
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306